name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create config file from secret
      run: |
        echo '${{ secrets.ARCADIA_CONFIG_JSONC }}' > arcadia-config.jsonc
        echo "ARCADIA_CONFIG_FILE=${{ github.workspace }}/arcadia-config.jsonc" >> $GITHUB_ENV
      shell: bash
    
    - name: Initialize environment
      run: scripts/init.sh
      shell: bash
    
    - name: Build for x64
      run: scripts/publish.sh x64
      shell: bash
      env:
        ARCADIA_CONFIG_FILE: ${{ env.ARCADIA_CONFIG_FILE }}
    
    - name: Build for arm64
      run: scripts/publish.sh arm64
      shell: bash
      env:
        ARCADIA_CONFIG_FILE: ${{ env.ARCADIA_CONFIG_FILE }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: arcadia
        path: |
          arcadia-x64.zip
          arcadia-arm64.zip
        if-no-files-found: error
    